import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'

const packageJson = JSON.parse(readFileSync(path.join(process.cwd(), 'package.json'), 'utf-8'))

const normalizeRepoUrl = (url: string) =>
  url
    .replace(/^git\+/, '')
    .replace(/^git:\/\//, 'https://')
    .replace(/^git@([^:]+):/, 'https://$1/')
    .replace(/\.git$/, '')

const repoUrl = packageJson.repository?.url ? normalizeRepoUrl(packageJson.repository.url) : undefined
const contact = repoUrl ?? packageJson.homepage ?? 'no-contact-provided'
const userAgent = `${packageJson.name}/${packageJson.version} (${contact})`

mkdirSync(path.join(process.cwd(), 'src/generated'), { recursive: true })
writeFileSync(
  path.join(process.cwd(), 'src/generated/userAgent.ts'),
  `// auto-generated by scripts/generate-user-agent.ts — do not edit
  export const USER_AGENT = ${JSON.stringify(userAgent)}
  export const APP_NAME = '${packageJson.name}'
  export const APP_VERSION = '${packageJson.version}'
  export const APP_CONTACT = '${contact}'
  `,
)
